<?php

function ensureDefaultResearchProjects(PDO $pdo): void {
    $seedProjects = [
        [
            'id' => 6,
            'title' => 'Post Correspondence Problem (PCP) Solver',
            'category' => 'Models of Computation',
            'year' => '2024',
            'shortDescription' => 'A computational tool exploring undecidability through the Post Correspondence Problem.',
            'longDescription' => 'An interactive solver and visualization for the Post Correspondence Problem (PCP), a classic undecidable problem in formal language theory. The tool allows users to define tile sets and attempt to find matching sequences, demonstrating the complexity of computational limits.',
            'techStack' => ['JavaScript', 'Theory of Computation', 'Algorithms', 'Formal Languages'],
            'highlights' => ['Undecidability Exploration', 'Interactive Tile Matching', 'Formal Language Theory Visualization'],
            'links' => ['demo' => 'https://tanuiksila.co.ke/PCP/', 'github' => '#'],
        ],
        [
            'id' => 7,
            'title' => 'Context-Free Chaos',
            'category' => 'Models of Computation',
            'year' => '2024',
            'shortDescription' => 'Visualization of context-free grammar production and visual complexity.',
            'longDescription' => 'A project exploring the intersection of formal grammar systems and visual complexity. It visualizes the derivation process of context-free grammars (CFGs), showing how simple production rules can lead to intricate, chaotic structures.',
            'techStack' => ['JavaScript', 'CFG', 'Automata Theory', 'Visualization'],
            'highlights' => ['Grammar Derivation Visualization', 'Complexity Analysis', 'Automata Theory Implementation'],
            'links' => ['demo' => 'https://tanuiksila.co.ke/ContextFreeChaos/', 'github' => '#'],
        ],
        [
            'id' => 8,
            'title' => 'Graph Coloring Machine',
            'category' => 'Models of Computation',
            'year' => '2024',
            'shortDescription' => 'Interactive tool demonstrating vertex coloring algorithms on complex graphs.',
            'longDescription' => 'An interactive simulation of graph coloring problems. It visualizes how algorithms assign colors to graph vertices such that no two adjacent vertices share the same color, effectively demonstrating concepts of chromatic numbers and constraint satisfaction in graph theory.',
            'techStack' => ['JavaScript', 'Graph Theory', 'Algorithms', 'React'],
            'highlights' => ['Vertex Coloring Visualization', 'Chromatic Number Calculation', 'Interactive Graph Manipulation'],
            'links' => ['demo' => 'https://silatanui.github.io/Graph-Coloring-Machine/', 'github' => 'https://github.com/silatanui/Graph-Coloring-Machine'],
        ],
        [
            'id' => 9,
            'title' => 'The Enumerator',
            'category' => 'Models of Computation',
            'year' => '2024',
            'shortDescription' => 'Simulation of set enumeration and computability theory concepts.',
            'longDescription' => 'An educational tool exploring the concept of enumerators in computability theory. It visualizes how Turing machines or algorithms can systematically list members of a countable set, helping to bridge the gap between abstract theoretical concepts and visual understanding.',
            'techStack' => ['JavaScript', 'Computability Theory', 'Automata', 'Set Theory'],
            'highlights' => ['Set Enumeration Logic', 'Turing Completeness Concepts', 'Theory Visualization'],
            'links' => ['demo' => 'https://silatanui.github.io/Enumerator/', 'github' => 'https://github.com/silatanui/Enumerator'],
        ],
        [
            'id' => 10,
            'title' => 'Entscheidungsproblem',
            'category' => 'Models of Computation',
            'year' => '2024',
            'shortDescription' => 'Exploration of Hilbert\'s Decision Problem and logical validity.',
            'longDescription' => 'A project dedicated to David Hilbert\'s Entscheidungsproblem (Decision Problem). It explores the limits of algorithmic logic and the historical context of Turing\'s proof regarding the undecidability of first-order logic, visualized through interactive logical constructs.',
            'techStack' => ['JavaScript', 'Logic', 'Formal Systems', 'History of Math'],
            'highlights' => ['First-Order Logic', 'Undecidability Visualization', 'Turing Machine Concepts'],
            'links' => ['demo' => 'https://silatanui.github.io/Entscheidungsproblem/', 'github' => 'https://github.com/silatanui/Entscheidungsproblem'],
        ],
        [
            'id' => 11,
            'title' => 'Hilbert\'s 10th Problem',
            'category' => 'Models of Computation',
            'year' => '2024',
            'shortDescription' => 'Visualizing Diophantine equations and algorithmic solvability.',
            'longDescription' => 'A computational exploration of Hilbert\'s 10th Problem regarding the solvability of Diophantine equations. This tool helps visualize integer solutions and discusses the Matiyasevich-Robinson-Davis-Putnam (MRDP) theorem through code and interactive examples.',
            'techStack' => ['JavaScript', 'Number Theory', 'Diophantine Equations', 'Math'],
            'highlights' => ['Integer Solutions Finder', 'MRDP Theorem Visualization', 'Mathematical Logic'],
            'links' => ['demo' => 'https://silatanui.github.io/Hilbert-s-10th-Problem/', 'github' => 'https://github.com/silatanui/Hilbert-s-10th-Problem'],
        ],
        [
            'id' => 1,
            'title' => 'AI-Driven E-Commerce Automation',
            'category' => 'AI/ML',
            'year' => '2024 - Present',
            'shortDescription' => 'Master\'s thesis project automating e-commerce workflows using AI and Blazor Server.',
            'longDescription' => 'Master\'s thesis project focusing on automating e-commerce workflows using AI technologies and Blazor Server framework. Implementing intelligent product recommendations, inventory management, and customer behavior analysis.',
            'techStack' => ['Blazor Server', 'C#', 'AI/ML', 'ASP.NET Core', 'Entity Framework'],
            'highlights' => ['Intelligent Recommendations', 'Inventory Management', 'Customer Behavior Analysis'],
            'links' => ['demo' => '#', 'github' => '#'],
        ],
        [
            'id' => 2,
            'title' => 'Global AI Impact Visualization',
            'category' => 'Visualization',
            'year' => '2025',
            'shortDescription' => 'Interactive map visualizing global AI adoption rates and economic impact.',
            'longDescription' => 'A comprehensive visualization dashboard presenting AI adoption metrics across 5000+ data points. Features an interactive choropleth map and filtering system to explore AI adoption rates and consumer trust levels.',
            'techStack' => ['D3.js', 'GeoJSON', 'React', 'Data Analysis'],
            'highlights' => ['5000+ Data Points', 'Global Choropleth Map', 'Industry-specific Filtering'],
            'links' => ['demo' => 'https://tanuiksila.co.ke/global_ai_impact_visualization/', 'github' => '#'],
        ],
        [
            'id' => 3,
            'title' => 'The AI Purple Problem',
            'category' => 'Visualization',
            'year' => '2025',
            'shortDescription' => 'Analysis of AI vs. Human design bias, revealing AI\'s strong preference for purple hues.',
            'longDescription' => 'A data visualization study analyzing color patterns in AI-generated designs. Findings reveal a distinct bias towards the purple-violet spectrum and high saturation, contrasting with human designer palettes.',
            'techStack' => ['D3.js', 'Python', 'Data Visualization', 'Color Analysis'],
            'highlights' => ['AI Color Bias Analysis', 'Hue & Saturation Clustering', 'Interactive Bubble Charts'],
            'links' => ['demo' => 'https://tanuiksila.co.ke/ai_purple_problem/', 'github' => '#'],
        ],
        [
            'id' => 4,
            'title' => 'Interactive Curve Design System',
            'category' => 'Geometric Modelling',
            'year' => '2025',
            'shortDescription' => 'Advanced parametric curve visualization system for Bézier and B-Spline algorithms.',
            'longDescription' => 'An interactive system for designing and analyzing parametric curves. Implements multiple algorithms including Bézier (De Casteljau), Hermite, and B-Splines with real-time differential geometry analysis.',
            'techStack' => ['JavaScript', 'Canvas API', 'Computational Geometry', 'Linear Algebra'],
            'highlights' => ['Real-time Curvature Analysis', 'Dynamic Tangent Control', 'Multiple Spline Types'],
            'links' => ['demo' => 'https://tanuiksila.co.ke/CAGD_P1/', 'github' => '#'],
        ],
        [
            'id' => 5,
            'title' => 'Least Squares Curve Approximation',
            'category' => 'Geometric Modelling',
            'year' => '2025',
            'shortDescription' => 'System for fitting Cubic Bézier curves to noisy data points using numerical methods.',
            'longDescription' => 'A mathematical modeling tool that fits a parametric curve to a large set of noisy data points using Linear Algebra (Normal Equations, Gaussian Elimination).',
            'techStack' => ['JavaScript', 'Linear Algebra', 'Numerical Methods', 'Data Fitting'],
            'highlights' => ['Least Squares Algorithm', 'Gaussian Elimination', 'Noise Reduction'],
            'links' => ['demo' => 'https://tanuiksila.co.ke/CAGD_Approx/', 'github' => '#'],
        ],
    ];

    $stmt = $pdo->prepare('INSERT INTO `research_projects` (`source_id`, `title`, `category`, `year_label`, `short_description`, `long_description`, `tech_stack_json`, `highlights_json`, `demo_url`, `github_url`, `sort_order`, `is_active`) VALUES (:source_id, :title, :category, :year_label, :short_description, :long_description, :tech_stack_json, :highlights_json, :demo_url, :github_url, :sort_order, 1) ON DUPLICATE KEY UPDATE `title` = VALUES(`title`), `category` = VALUES(`category`), `year_label` = VALUES(`year_label`), `short_description` = VALUES(`short_description`), `long_description` = VALUES(`long_description`), `tech_stack_json` = VALUES(`tech_stack_json`), `highlights_json` = VALUES(`highlights_json`), `demo_url` = VALUES(`demo_url`), `github_url` = VALUES(`github_url`), `sort_order` = VALUES(`sort_order`), `is_active` = 1');

    $sortOrder = 0;
    foreach ($seedProjects as $project) {
        $stmt->execute([
            ':source_id' => (int) $project['id'],
            ':title' => (string) $project['title'],
            ':category' => (string) $project['category'],
            ':year_label' => (string) $project['year'],
            ':short_description' => (string) $project['shortDescription'],
            ':long_description' => (string) $project['longDescription'],
            ':tech_stack_json' => json_encode($project['techStack'], JSON_UNESCAPED_UNICODE),
            ':highlights_json' => json_encode($project['highlights'], JSON_UNESCAPED_UNICODE),
            ':demo_url' => (string) ($project['links']['demo'] ?? ''),
            ':github_url' => (string) ($project['links']['github'] ?? ''),
            ':sort_order' => $sortOrder,
        ]);
        $sortOrder++;
    }
}
